/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projfactura.formularios;

import projfactura.formularios.consultas.FrmConsultaClientes;
import projfactura.formularios.consultas.FrmConsultaFacturas;
import projfactura.formularios.consultas.FrmConsultaProductos;
import javafx.application.Application;
import javax.swing.JFrame;
import projfactura.formularios.mantenimientos.FrmClientes;
import projfactura.formularios.mantenimientos.FrmFacturas;
import projfactura.formularios.mantenimientos.FrmProductos;

/**
 *
 * @author Phenom
 */
public class FrmPrincipal extends JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        mnProductos = new javax.swing.JMenu();
        ConsultaClientes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MantProductos = new javax.swing.JMenu();
        MantenimientoClientes = new javax.swing.JMenuItem();
        MantenimientoFacturas = new javax.swing.JMenuItem();
        MantenimientoProductos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btnAcerca = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Archivo");

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu3.add(btnSalir);

        jMenuBar2.add(jMenu3);

        mnProductos.setText("Consultas");

        ConsultaClientes.setText("Clientes");
        ConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaClientesActionPerformed(evt);
            }
        });
        mnProductos.add(ConsultaClientes);

        jMenuItem2.setText("Facturas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnProductos.add(jMenuItem2);

        jMenuItem3.setText("Productos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnProductos.add(jMenuItem3);

        jMenuBar2.add(mnProductos);

        MantProductos.setText("Mantenimientos");

        MantenimientoClientes.setText("Clientes");
        MantenimientoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoClientesActionPerformed(evt);
            }
        });
        MantProductos.add(MantenimientoClientes);

        MantenimientoFacturas.setText("Facturas");
        MantenimientoFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoFacturasActionPerformed(evt);
            }
        });
        MantProductos.add(MantenimientoFacturas);

        MantenimientoProductos.setText("Productos");
        MantenimientoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoProductosActionPerformed(evt);
            }
        });
        MantProductos.add(MantenimientoProductos);

        jMenuBar2.add(MantProductos);

        jMenu5.setText("Ayuda");

        btnAcerca.setText("Acerca");
        jMenu5.add(btnAcerca);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void MantenimientoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoClientesActionPerformed
        new FrmClientes().setVisible(true);
    }//GEN-LAST:event_MantenimientoClientesActionPerformed

    private void MantenimientoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoProductosActionPerformed
        new FrmProductos().setVisible(true);
    }//GEN-LAST:event_MantenimientoProductosActionPerformed

    private void MantenimientoFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoFacturasActionPerformed
        new FrmFacturas().setVisible(true);
    }//GEN-LAST:event_MantenimientoFacturasActionPerformed

    private void ConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaClientesActionPerformed
        new FrmConsultaClientes().setVisible(true);
    }//GEN-LAST:event_ConsultaClientesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new FrmConsultaProductos().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new FrmConsultaFacturas().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsultaClientes;
    private javax.swing.JMenu MantProductos;
    private javax.swing.JMenuItem MantenimientoClientes;
    private javax.swing.JMenuItem MantenimientoFacturas;
    private javax.swing.JMenuItem MantenimientoProductos;
    private javax.swing.JMenuItem btnAcerca;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu mnProductos;
    // End of variables declaration//GEN-END:variables
}
